### ISSUE TITLE
Cannot find 'Virtual Display tab' in Ubuntu Displays Setting

### ISSUE THREAD

**Issue by bossm0n5t3r** [kbumsik/VirtScreen#20]
I just following your 'Installation - Debian(Ubuntu)' and 'How to use' steps, but there is a problem that I cannot solve.

When I press "Enable virual screen" button in app, then alert following message.

> No virtual screen selected.
> Go to Display->Virtual Display->Advaced
> To select a device.

But in my ubuntu 18.04.1, there is no display tab such as virtual ~~.

How could I solve this problem?

**Comment by kbumsik** [comment]
Which GPU and graphic driver are you using?

**Comment by bossm0n5t3r** [comment]
![screenshot from 2018-10-31 19-03-50](https://user-images.githubusercontent.com/38637046/47781001-0537f980-dd40-11e8-8a6e-c9892b8a54c6.png)
---
![screenshot from 2018-10-31 19-07-00](https://user-images.githubusercontent.com/38637046/47781111-45977780-dd40-11e8-9b27-1f57d4ce4384.png)
---

these two screen shots are my current settings, but there is no "Advanced" button.

Could I install another programs? BTW, sorry to my understanding... I'm noob for programming...

**Comment by kbumsik** [comment]
![image](https://user-images.githubusercontent.com/7823583/47842014-cfa61580-ddfe-11e8-89b8-76f6d7b881aa.png)
![image](https://user-images.githubusercontent.com/7823583/47842034-e187b880-ddfe-11e8-9e5e-17414f0a860d.png)

Oh I meant the "Advanced" button in out app.
If you cannot find VIRTUAL something in the device list, please tell me your GPU and graphic driver.
As a note, VirtScreen currently does not support Nvidia GPU with its proprietary diver. If you use a Nvidia GPU, you use use the open-source driver (called nouveau).

**Comment by bossm0n5t3r** [comment]
![screenshot from 2018-11-01 19-57-09](https://user-images.githubusercontent.com/38637046/47848125-a68e8080-de10-11e8-90ff-3f43073a77a5.png)
---

You're right. now, I use Notebook 9 Always model(NT900X5T-X716A) in samsung, and graphic driver is Nvidia.

I check driver in setting after your suggestion, but it already use nouveau driver(above picture)... right?

But, the situation is same. there is no such "VIRTUAL1" in the list.

Maybe I should find another way.

Thank you for your help. I'm very impressed with your project and this program. I hope to be a good programmer like you.

**Comment by kappithannemo** [comment]
I cannot find VIRTUAL something in the device list.
My graphics is Intel® HD Graphics 3000 (SNB GT2).
i m using ubuntu 20.04 .
in the device list, there is lvds-1 which is unselectable. There is vga-1 which can be selected but when i click enable virtual screen, it returns the error,
['xrandr', '--output', 'VGA-1', '--mode', '1600x2560_virt']
xrandr: Configure crtc 1 failed
what shall i do? please suggest a solution.
