### ISSUE TITLE
How do i use this on Fedora 29?

### ISSUE THREAD

**Issue by m00nwtchr** [kbumsik/VirtScreen#35]
I am using Fedora 29 and I'm currently getting a "Currently Wayland is not supported" error. Should I uninstall it and replace with something different? Or when will it be supported?

**Comment by cristianopimentel** [comment]
Hi @lukas2005, if you don't mind to log in in your session using XOrg:
In the login screen, there is a small gear icon where you can pick how you want to login in into gnome.
Should be something like this -> https://itsfoss.com/switch-xorg-wayland/

Have fun.

**Comment by m00nwtchr** [comment]
When i try to login in after switching the screen just "glitches" out and returns to login 

EDIT: i think it was some kind of a bad config file. it works now

**Comment by m00nwtchr** [comment]
Now i don't have any VIRTUAL devices. Just HDMI and DVI-D (using nvidia gpu + nouveau driver + amd cpu)

**Comment by m00nwtchr** [comment]
Now i switched to NVIDIA drivers but not much changed

**Comment by fultonm** [comment]
Any alternatives to VirtScreen for newer versions of Fedora? I want to make another virtual desktop and share it to a tablet through VNC.
