### ISSUE TITLE
Error opening arandr

### ISSUE THREAD

**Issue by javibg6z** [kbumsik/VirtScreen#63]
Hi there!

I really love what this program can provide! kudos and thanks for the team!

But for the moment, i cannot make it work. I got some issues that seem to be fixed: I'm running Linux Mint 19.3, Nvidia GF117M and right after installation, I had no virtual connecton in virtScreen, which was fixed following some instructions provided in the issues section, I created the file 30-virtscreen.conf in xorg config folder, with the following code:

# nvidia/nouveau/amdgpu device should be configured first before Intel GPU
Section "Device"
	Identifier "nvidiagpu0"
	Driver     "nvidia" # Because you are using Nvidia proprietary driver. Change to "nouveau" if you are using open source nouveau driver
EndSection

# Then configure intel internal GPU
Section "Device"
	Identifier "intelgpu0"
	Driver     "intel"
	# You may put Option "VirtualHeads" "1" here but it seem you don't need to put this for Ubuntu 18.04.
EndSection

Now, I do have that virtual connection, but whenever i enable the virtual screen, i get an error in virtScreen: "Error opening arandr". I got that package installed and apparently working. I've tried to open that program, it shows two screens, I can create the VNC server apparently, but my devices don't make it to connect to the computer.

I feel i'm super close to make it work, but i'm stuck in this situation. I didn't get any threads with this issue neither, forgive me if I didn't search properly!

Does anybody have this problem? Any solutions to it? Thanks in advance!!

**Comment by javibg6z** [comment]
Alright! so, i somehow fixed the problem. And what seemed an Arandr problem, at the end that wasn't causing virtscreen to launch the thing. The problem came from Linux firewall, disabling it and done.

**Comment by azulaa** [comment]
Can you share that how did you solve it? Having same error...
